spring:
  application:
    name: ms-catalogo
  profiles:
    active: development
  config:
    import: optional:configserver:http://root:123456@localhost:7071

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
